# Using https://github.com/18F/uswds-jekyll
theme: uswds-jekyll

# OpenGraph / Twitter metadata
title: Dotgov.gov
description: Home of the DotGov.gov program, which operates the .gov DNS registry and zone.

# GA and GitHub data
google_analytics_ua: UA-99995535-1
repo: https://github.com/ir1x/dotgov-home

exclude:
- CONTRIBUTING.md
- _config.yml
- .travis.yml
- .gitignore
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor

styles:
  - /assets/css/main.css

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  pages:
    output: true
    #permalink: /:path/

kramdown:
  parse_block_html: true
